---
title: "Cleanup"
author: "Taylor Bonar"
date: "2022-07-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load large dataset
```{r}
library(tswge)
library(arrow)

assets_df = read.csv("data/asset_details.csv")
head(assets_df)

df = read_parquet("data/train_test.parquet")
head(df)
```

Extract the bitcoin dataset
```{r}
btc_df = df[df$Asset_ID == 1,]
head(btc_df)
```

Rename timestamp to properly be unix_time/epoch time
```{r}
names(btc_df)[names(btc_df) == "timestamp"] <- 'unix_time'
head(btc_df)
```

Create some timestamps for references
```{r}
library(lubridate)

btc_df$timestamp <- as.POSIXct(btc_df$unix_time, origin = "1970-01-01", tz="GMT")
head(btc_df)
tail(btc_df)
```

```{r}
dim(btc_df)
str(btc_df)
summary(btc_df)
```
Looks like for BTC we have 141,061 rows of data, with 10 features for 1 target.

Let's only grab the first month of data since we're tracking every minute update.
```{r}
btc_3month_2021 <- btc_df[btc_df$timestamp < as.Date("2021-06-01 00:00:00"),]
summary(btc_3month_2021)
```
```{r}
short_term <- btc_df[btc_df$timestamp > as.Date("2021-06-01") & btc_df$timestamp < as.Date("2021-06-02"),]
summary(short_term)
```

```{r}
long_term <- btc_df[btc_df$timestamp > as.Date("2021-06-01") & btc_df$timestamp < as.Date("2021-06-08"),]
summary(long_term)
```

```{r}
write_parquet(btc_3month_2021, sink="data/btc_3month_2021.parquet")
write_parquet(short_term, sink="data/btc_short_term_test.parquet")
write_parquet(long_term, sink="data/btc_long_term_test.parquet")
```