---
title: "Cleanup"
author: "Taylor Bonar"
date: "2022-07-22"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load large dataset
```{r}
library(tswge)
library(arrow)

assets_df = read.csv("data/asset_details.csv")
head(assets_df)

df = read_parquet("data/train.parquet.gzip")
head(df)
```

Extract the bitcoin dataset
```{r}
bitcoin_df = df[df$Asset_ID == 1,]
head(bitcoin_df)
```

Rename timestamp to properly be unix_time/epoch time
```{r}
names(bitcoin_df)[names(bitcoin_df) == "timestamp"] <- 'unix_time'
head(bitcoin_df)
```

Create some timestamps for references
```{r}
library(lubridate)

bitcoin_df$timestamp <- as.POSIXct(bitcoin_df$unix_time, origin = "1970-01-01", tz="GMT")
head(bitcoin_df)
```

```{r}
dim(bitcoin_df)
str(bitcoin_df)
summary(bitcoin_df)
```
Looks like for BTC we have 1,956,282 rows of data, with 10 features for 1 target.

Let's only grab the first month of data since we're tracking every minute update.
```{r}
btc_4month_2018
btc_jan2018 <- bitcoin_df[bitcoin_df$timestamp < as.Date("2018-05-01 00:00:00"),]
summary(btc_4month_2018)
```


```{r}
write_parquet(btc_jan2018, sink="data/bitcoin_01-2018.parquet")
write_parquet(bitcoin_df, sink="data/bitcoin_full.parquet")
```